### ISSUE TITLE
Modify Ghost theme/config

### ISSUE THREAD

**Issue by abelovic** [danielqiu/meteor-ghost#1]
Is there a way to modify a ghost theme and it's config file?

**Comment by danielqiu** [comment]
@abelovic 
It didn't support that in v0.5.0. I just updated it and it is supposed to suppose this feature, please update to the latest version (v0.5.2_2) and use it like:

```
ghost().then(function (ghostServer) {
  var config = ghostServer.config;
  // modify theme and config ...

  ghostServer.start();
});
```

**Comment by abelovic** [comment]
Thanks Daniel! 

I used your meteor-ghost-demo and it ran fine but I got errors when I tried adding the following:

```
  var config = ghostServer.config;

  config.paths.config = '/packages/ghost/config.js';
  config.paths.contentPath = '/packages/ghost/content/';
  config.paths.themePath = '/packages/ghost/content/themes';

  //This worked for my dev environment (I use nitrous)
  config.server = {
    host: '0.0.0.0',
    port: '8080'
  }
```

I added the casper theme in the packages so meteor would load everything. I want only the theme files locally so I can modify them independent of the ghost core.

Unfortunately this did not work for me - it kept giving me a file not found error. 
1. How can I get the root from within this context?
2. What settings should I override? I would ideally just want to point to my custom config file and not each property individually.
3. Should I put in packages folder like what I am doing or is there a better way to organize this in meteor so I can edit those files?

If you could add an example of how to connect to a local casper theme in your demo that would be very helpful

**Comment by danielqiu** [comment]
@abelovic 
I was writing the demo for your questions but got tied up with some urgent issue and I might not be able to revisit it until end of next week. Sorry for the waiting.

To use custom config file, you could do

```
ghost({
     config: path.join(__dirname, 'config.js')
});
```

before promise function. More code here:

```
if (Meteor.isServer) {

  Meteor.startup(function () {
    // code to run on server at startup

    var path = Npm.require('path');
    var __dirname = path.resolve('.');
    console.log("Current directory: ", __dirname);

    ghost({
          config: path.join(__dirname, 'config.js')
    });

    ghost().then(function (ghostServer) {

      var config = ghostServer.config;
      console.log(config);

      ghostServer.start();
    });
  });
}
```

**Comment by abelovic** [comment]
I changed the following:

var __dirname = process.env.PWD;

since it was giving me the root of the meteor folder where I want the root of the project.

however when I set this line:

```
ghost({
      config: path.join(__dirname, 'config.js')
});
```

I get the following error:

Warning: Ghost no longer starts automatically when using it as an npm module.

My path of the config file is correct because I am seeing the host (0.0.0.0), port (8080), and url but it will not run on the port I specified. Meteor starts up perfectly fine.

Do you know why this is happening? FYI I updated your package and even tried to bump it up to 0.5.10 which is currently the latest ghost release.

**Comment by danielqiu** [comment]
@abelovic 
I have updated [meteor-ghost-demo](https://github.com/danielqiu/meteor-ghost-demo) to show how to support local config.js file and themes. Please pull the latest code of the demo and give it a try to see if it works on your end. Then we could start from here.

According to [this](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module#update), using Ghost as an NPM module only support up to 0.5.2 at the moment, thus you can't use 0.5.10.

**Comment by abelovic** [comment]
Thanks Daniel for making the updates! I got the new code but unfortunately it's still not working for me. I'm not sure what I am doing wrong? :/

The only thing I changed was the development environment settings in the config.js file. I changed:

url: http://<myboxname>.usw1.nitrousbox.com

server.host: 0.0.0.0

server.port: 4000

Still end up with the same issue where it will connect to meteor but not to ghost on the specified port (when it loads it does say it's listening on that port). 

Also still getting the warning "Ghost no longer starts automatically when using it as an npm module."

Did you get this to load? If so it would have to be something to do with nitrous?

**Comment by danielqiu** [comment]
It worked on my local machine. When you tried on local without any changes, did it work as expected?

BTW, your url looks like having an extra . before usw1.

The warning could be ignored.

**Comment by abelovic** [comment]
Hi Daniel,

Turns out my network was blocking everything but port 80. I was also using Nitrous lite where you do not have root access. Since then Nitrous have changed their service to a pro version which does allow root access. So now I am able to install nginx which allows me to send everything over port 80 and redirect to whatever port I need. To access ghost I just run it in a folder called blog.

Good news is this works. Bad news is I cannot get an actual theme to run. When you navigate to the ghost blog it throws an error saying it cannot load a default theme. So I added casper but this results in dependency errors now i.e. JQuery is not defined.

I tried putting the entire content folder in the meteor public and client folders which fixed the dependency errors but then I get a 404 page cannot be found error when trying to access ghost.

Do you know how I can fix this? You should be able to replicate in your environment by just adding the casper theme.

My config.js

```
development: {

    url: 'http://<my app instance>.nitrousapp.com',

    database: {
        client: 'sqlite3',
        connection: {
            filename: path.join(__dirname, '/client/content/data/ghost-dev.db')
        },
        debug: false
    },
    server: {
        host: '0.0.0.0',
        port: '2368'
    },
    paths: {
        contentPath: path.join(__dirname, '/client/content/')
    }
}
```

P.S. It may be useful to add a content/themes/casper submodule to your demo for the default theme just like ghost does. That way it would be easy to get the latest casper updates when getting your project

**Comment by foobarbecue** [comment]
Running the meteor-ghost-demo locally on 64-bit ubuntu 14.10 I get: "ERROR: The currently active theme casper is missing." Is that this issue?

**Comment by abelovic** [comment]
Yes this is what I get as well. 

So I added the casper theme but now I either get a javascript error caused by dependencies in the theme (jQuery is undefined) or if I add the content folder to meteor's built in folder i.e. client the error goes away (since meteor loads it in the correct order) except ghost doesn't figure out the path correctly.

Probably just something simple I am missing ;)

**Comment by danielqiu** [comment]
@abelovic @foobarbecue 
Yeah, I should've added the default theme for the ease of use. I recently just changed a new job and didn't have a chance to take a look at this problem.

I am hoping if there is anyone out there who could help on this before I find some time, or you could figiure it out yourself. :)

**Comment by danielqiu** [comment]
@abelovic @foobarbecue 
I've added the default theme to the demo app. please pull the latest version and also run
git submodule update --init

I found that if you git pull for the first time, you might run into an error, but exit meteor and restart meteor fix the issue. I might look into that glitch a bit later.

**Comment by krishnaff** [comment]
Hello, 
Anyone familiar with this issue?

```
npm ERR! node v0.10.36
npm ERR! npm  v2.14.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/Casper
npm ERR! 404 
npm ERR! 404 'Casper' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 It was specified as a dependency of 'testmeteorapp'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I'm trying to deploy it on Modulus alongside my existing meteor app. Any pointers please?
Thanks.
