### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ionm** [danielqiu/meteor-ghost#3]
I have tried installing this package under both Windows and Ubuntu and in each case I get the same error:

While checking for mrt:ghost@0.5.2_2:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

I am running Meteor 1.1.0.2

**Comment by danielqiu** [comment]
@ionm 
Your Ubuntu might be 32-bit intel, which I didn't have luck to build on meteor's 32-bit VM. I managed to build it this time. Please update to mrt:ghost@0.5.2_3 and check again.

There is still a problem with the Windows build at the moment though.

**Comment by emptyway** [comment]
got this error under OS X as well. Meteor 1.1.0.2

```
 => Errors while adding packages:

While checking for mrt:ghost@0.5.2_3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by thetechnaddict** [comment]
+1

**Comment by bitsoflogic** [comment]
+1 ubuntu

**Comment by danielqiu** [comment]
@ionm @simonlinj @thetechnaddict @bitsoflogic 
I've rebuilt it for OS X, ubuntu 32 and 64. Please use the latest version mrt:ghost@0.6.4
