### ISSUE TITLE
How to deploy on Modulus.io running an existing app?

### ISSUE THREAD

**Issue by krishnaff** [danielqiu/meteor-ghost#4]
Hello, 

This is the only atmosphere available package of ghost, thanks for that!
I was able to quickly setup the blog on localhost and everything works perfectly. 

Any pointers on setting this up alongside an existing meteor app running on Modulus.io please? I did deploy it and it deploys without errors, but I'm unable to access the http://localhost:2368/ version of the URL on modulus.

Is there some special setup needed?  Also I have come across this http://blog.modulus.io/ghost-blog-on-modulus
Does this mean, Ghost won't work with Mongo?
Any ideas in the right direction would be really appreciated! Thanks!

**Comment by danielqiu** [comment]
Thanks for using the package!
I am sorry but I don't have any experience of running Modulus.io.

**Comment by krishnaff** [comment]
Hello @danielqiu 
Thanks for your response. Does any of these errors look familiar to you?

```
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/mnt/home/.nvm/v0.10.36/bin/npm" "install" "--production" "--quiet"
npm ERR! node v0.10.36
npm ERR! npm  v2.14.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/Casper
npm ERR! 404 
npm ERR! 404 'Casper' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 It was specified as a dependency of 'speedhiringwebsite'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Sorry to still continue on this, but I'm really keen on setting up Ghost blog on my existing meteor application. 
Modulus.io is a developer friendly hosting provider for meteor apps. Never had trouble running any of my previous meteor apps there.
Ghost works fine on localhost, the problem is only when deploying. If its a generic NPM issue, then maybe it can be solved without going too much into Modulus.io. Thanks again for your time!
